### ISSUE TITLE
语言简写问题

### ISSUE THREAD

**Issue by XQDD** [hujingshuang/MTrans#4]
法语是French，应该不是Fra吧
可以参考chrome的语言双字母简写
https://src.chromium.org/viewvc/chrome/trunk/src/third_party/cld/languages/internal/languages.cc

**Comment by hujingshuang** [comment]
@XQDD 你好，Google 翻译中 sl 字段表示 source language，tl 字段表示 translation language，这些信息可以 F12 键 -> NetWork中查看到， Google 翻译用的是 fr 表示法语。
由于各在线翻译的语言表示并不统一，因此在本项目中对语言进行了规范，你可以通过修改代码进行自行调整，很方便的。

**Comment by XQDD** [comment]
嗯，可以的，自己改代码了
